@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}

###
POST http://{{host}}/api/register HTTP/1.1
content-type: application/json

{
  "identification-number": "1234",
  "names": "John Doe",
  "password": "1234"
}

###

POST http://{{host}}/api/login HTTP/1.1
content-type: application/json

{
  "identification-type": "2",
  "identification-number": "8d409ae4d8400d8e",
  "password": "denizDogan@whitebutterfly739.com"
}